function [A,B] = autoGen_simpleCarLinDyn(x,y,q1,q2,v,fd,u2,u1,u3,l,a,b,m,J,tau)
%AUTOGEN_SIMPLECARLINDYN
%    [A,B] = AUTOGEN_SIMPLECARLINDYN(X,Y,Q1,Q2,V,FD,U2,U1,U3,L,A,B,M,J,TAU)

%    This function was generated by the Symbolic Math Toolbox version 7.2.
%    21-Apr-2018 19:47:12

t2 = 1.0./l;
t3 = sin(q1);
t4 = tan(q2);
t5 = cos(q1);
t6 = t5-b.*t2.*t3.*t4;
t7 = t4.^2;
t8 = t7+1.0;
t9 = b.*t2.*t4.*t5;
t10 = t3+t9;
t11 = 1.0./tau;
t12 = b.^2;
t13 = m.*t12;
t14 = J+t13;
t15 = l.^2;
t16 = m.*t15;
t17 = t7.*t14;
t18 = t16+t17;
t19 = cos(q2);
t20 = 1.0./t19.^2;
t21 = 1.0./t18;
t22 = q2.*t11;
t25 = t11.*u2;
t23 = t22-t25;
t24 = 1.0./t18.^2;
A = reshape([0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-t10.*v,t6.*v,0.0,0.0,0.0,0.0,0.0,-b.*t2.*t3.*t8.*v,b.*t2.*t5.*t8.*v,t2.*t8.*v,-t11,fd.*t4.*t8.*t14.*t15.*t24.*-2.0-t4.*t11.*t14.*t20.*t21.*v-t8.*t14.*t20.*t21.*t23.*v-t4.*t14.*1.0./t19.^3.*t21.*t23.*v.*sin(q2).*2.0+t7.*t8.*t14.^2.*t20.*t23.*t24.*v.*2.0,0.0,0.0,t6,t10,t2.*t4,0.0,-t4.*t14.*t20.*t21.*t23,0.0,0.0,0.0,0.0,0.0,0.0,t15.*t21,0.0,0.0,0.0,0.0,0.0,t11,t4.*t11.*t14.*t20.*t21.*v,0.0,0.0],[7,7]);
if nargout > 1
    B = reshape([0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0],[7,2]);
end
